#!/usr/bin/env docker-compose -f 

---
version: "3.7"
services:
  s1: &default_config
    image: chusiang/ansible-managed-node:ubuntu-14.04
    container_name: server1
    ports:
      - "2221:22"
    restart: always
    networks:
      - my-ansible-play
  s2:
    <<: *default_config
    container_name: server2
    ports:
      - "2222:22"

networks:
  my-ansible-play:
