#!/usr/bin/env ansible-playbook

- name: stardust crusaders
  hosts: all
  tasks:
    - name: hello dio
      command: echo 'the world~~~~'
      register: info
    - name: hello jojo
      when: ansible_pkg_mgr == 'apt'
      debug:
        msg: "oraoraoraora!!!!"
    - debug:
        var: info
      when: ansible_pkg_mgr == 'yum'

- name: diamond unbreakable
  hosts: dev
  vars:
    dynamic_word: "dorarararara!!"
  # vars_files:
  #   - /vars/external_vars.yml
  tasks:
    - name: generate wry file
      template:
        src: templates/jojotemplate.j2
        dest: /tmp/wry.txt
    - name: show wry file
      command: cat /tmp/wry.txt
      register: wry_result
      notify: 'echos action 1'
    - name: print wry stdout
      debug:
        msg: "wry_result: {{ wry_result.stdout_lines }}"
  post_tasks:
    - name: echos action finale
      debug:
        msg: "echos finale~~~~~"
  handlers:
    - name: echos action 1
      debug:
        msg: "echos handler, only executed once after all tasks~~~~~~"
  

