#!/usr/bin/env ansible-playbook

- name: stardust crusaders 
  hosts: all
  tasks:
    - name: hello dio
      command: echo 'the world~~~~'
      register: info
    - name: hello jojo
      debug:
        msg: 'oraoraoraora!!!!'
    - debug:
        var: info
