#!/usr/bin/env ansible-playbook

---
# this is 1st play
- name: stardust crusaders
  hosts: non-prod
  # become: true
  become_user: root
  roles:
    - new-stand
    - print-author
    - best-enemy
  pre_tasks:
    - name: hello dio
      command: echo 'the world~~~~'
      register: info
      tags:
        - prefer-role-over-tag
  tasks:
    - debug:
        # tenary, using ansible setup module facts
        msg: "hello jojo~~~{{ info.stdout if ansible_pkg_mgr is defined and ansible_pkg_mgr == 'apt' 
              else 'oraoraoraora~~~~' }}"
      when: info.stdout is defined
  # if set to 50%, this play will run 1 server at a time.
  serial: "100%"
  max_fail_percentage: 30


# this is 2nd play
- name: diamond unbreakable
  hosts: dev
  gather_facts: no
  roles:
    - print-author
    - best-enemy
  vars:
    dynamic_word: "dorarararara!!"
  # vars_files:
  #   - /vars/external_vars.yml
  tasks:
    - include: tasks/wryyy.yml
  post_tasks:
    - name: ed credits
      debug:
        msg: ~~~~ name={{ item.key }}, stand={{ item.value }} ~~~~
      with_dict: "{{ stand_users }}"
      # detect changes of status
      when: wry_result.changed
  handlers:
    - name: echos action 1
      debug:
        msg: "echos handler, only executed once after all tasks~~~~~~"
  

