#!/usr/bin/env ansible-playbook

---
# this is 1st play
- name: stardust crusaders
  hosts: local
  roles:
    - new-stand
    - print-author
    - best-enemy
  tasks:
    - name: hello dio
      command: echo 'the world~~~~'
      register: info
      tags:
        - prefer-role-over-tag
    - name: hello jojo
      debug:
        msg: "oraoraoraora!!!!"
      when: ansible_pkg_mgr == 'apt'
    - debug:
        var: info
      when: ansible_pkg_mgr == 'yum'


# this is 2nd play
- name: diamond unbreakable
  hosts: dev
  roles:
    - print-author
    - best-enemy
  vars:
    dynamic_word: "dorarararara!!"
  # vars_files:
  #   - /vars/external_vars.yml
  tasks:
    - name: generate wry file
      template:
        src: templates/jojotemplate.j2
        dest: /tmp/wry.txt
    - name: show wry file
      command: cat /tmp/wry.txt
      register: wry_result
      notify: 'echos action 1'
    - name: print wry stdout
      debug:
        msg: "wryyyy count={{ item }}, {{ wry_result.stdout_lines }}"
      with_sequence: start=1 end=4 stride=2
      when: not ansible_check_mode
  post_tasks:
    - name: ed credits
      debug:
        msg: ~~~~ name={{ item.name }}, stand={{ item.stand }} ~~~~
      with_items:
        - { name: 'Koichi Hirose', stand: 'Echoes'}
        - { name: 'Okuyasu Nijimura', stand: 'The Hand'}
  handlers:
    - name: echos action 1
      debug:
        msg: "echos handler, only executed once after all tasks~~~~~~"
  

