---
- name: generate wry file
  template:
    src: templates/jojotemplate.j2
    dest: /tmp/wry.txt
- name: show wry file
  command: cat /tmp/wry.txt
  register: wry_result
  notify: 'echos action 1'
- name: print wry stdout
  debug:
    msg: "wryyyy count={{ item }}, {{ wry_result.stdout_lines }}"
  with_sequence: start=1 end=4 stride=2
  when: not ansible_check_mode