server:
    port: 8081
    servlet:
        context-path: /precure

spring:
    devtools:
        restart:
            additional-paths: src/main/resources
            poll-interval: 10000

app:
    service-name: PrecureApp
    service-desc: An webapp for precures
    enable-swagger: true

knife4j: # not working with swagger2. springfox issue.
    enable: true
    setting:
        language: en-US