#### General
server:
    port: 8081
    servlet:
        context-path: /precure

spring:
    devtools:
        restart:
            additional-paths: src/main/resources
            poll-interval: 2000

